force-app/main/default/objects/Restaurant_Location__c/Restaurant_Location__c.object-meta.xml
<CustomObject>
    <label>Restaurant Location</label>
    <nameField>
        <label>Restaurant Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurant Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Restaurant Locations</relationshipLabel>
    <relationshipName>Restaurant_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Restaurant_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Restaurant_Locations_Domain_Test.cls
@isTest
public class Restaurant_Locations_Domain_Test {
    @isTest
    public static void testgetRestaurantLocationById() {
        Account testAccount = new Account(Name = 'testAccount'); 
        insert testAccount;
        String testAccountId = testAccount.Id;
        Restaurant_Location__c testRestaurant = new Restaurant_Location__c();
        Restaurant_Location__c testData = new Restaurant_Location__c(
            Name = 'testData', status__c = 'Active', Account__c = testAccountId, 
            Address__c = 'Dubai', Region__c = 'East', Last_Visit_Date__c = Date.today()
        );
        insert testData;
        Test.startTest();
         testRestaurant = Restaurant_Locations_Domain.getRestaurantLocationById(
           new Set<Id>{testData.Id}
         )[0];
        Test.stopTest();
        System.assertEquals(testRestaurant.Id, testData.Id);
        System.assertEquals(testRestaurant.Status__c, testData.Status__c);
        System.assertEquals(testRestaurant.Account__c, testData.Account__c);
        System.assertEquals(testRestaurant.Last_Visit_Date__c, testData.Last_Visit_Date__c);
    }
}