force-app/main/default/objects/Restaurant_Location__c/Restaurant_Location__c.object-meta.xml
<CustomObject>
    <label>Restaurant Location</label>
    <nameField>
        <label>Restaurant Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurant Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestaurantLocationTriggerTest.cls
@isTest
private class RestaurantLocationTriggerTest {
    


    @isTest
    static void testLiveDateSet() {
    	Restaurant_Location__c testLocation = new Restaurant_Location__c();
        testLocation.Name = 'Test Location 1';
        testLocation.Region__c = 'East';
        testLocation.Status__c = 'Active';
        insert testLocation;
        test.startTest();
        System.assertEquals(testLocation.Last_Visit_Date__c, Date.Today(), 'Last_Visit_Date__c should be set to Today');
        test.stopTest();
    }
}