force-app/main/default/objects/Restaurant_Location__c/Restaurant_Location__c.object-meta.xml
<CustomObject>
    <label>Restaurant Location</label>
    <nameField>
        <label>Restaurant Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurant Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Restaurant Locations</relationshipLabel>
    <relationshipName>Restaurant_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Restaurant_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Restaurant_Locations_Domain.cls
public with sharing class Restaurant_Locations_Domain {

    public static List<Restaurant_Location__c> getRestaurantLocationById(Set<Id> restaurantId) {
        return [
            SELECT
                Id,
                Account__c,
                Last_Visit_Date__c,
                Status__c
            FROM
                Restaurant_Location__c
            WHERE
                Id = :restaurantId
        ];
    }
}